fix: cannot find module '.prisma/client/index'
Runtime.ImportModuleError: Error: Cannot find module '.prisma/client/index'
Require stack:
- /var/task/node_modules/@prisma/client/index.js
- /var/task/.netlify/functions-internal/server.js
- /var/task/server.js
- /var/runtime/index.mjs
    at _loadUserApp (file:///var/runtime/index.mjs:1000:17)
    at Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1035:21)
    at start (file:///var/runtime/index.mjs:1200:23)
    at file:///var/runtime/index.mjs:1206:1